# Generated by Django 5.0.7 on 2026-07-17 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='taskshare',
            name='unique_share_per_task_user',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskshare',
            unique_together={('task', 'shared_with')},
        ),
    ]
